# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许推送代码
      packages: read   # 允许读取包

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # - name: Auto Update
    #   run: |
    #     echo "auto update start" >> github_actions.log
    #     > github_actions.log
    #     sh auto_run.sh ${{ secrets.GITHUB_TOKEN }} >> github_actions.log
    #     echo "auto update end" >> github_actions.log

    - name: Generate summary
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Generate summary start" >> github_actions.log
        > github_actions.log
        python main.py >> github_actions.log
        echo "Generate summary end" >> github_actions.log

    - name: Commit
      run: |
        echo "commit&push start" >> github_actions.log
        git config --global user.email uxiaopeng@gmail.com
        git config --global user.name yuxiaopeng
        git add .
        git commit -m"action:`date`"
        git push
        echo "commit&push end" >> github_actions.log